//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.10.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ufAssociatedPage"
	/// <summary>UF.AssociatedPage</summary>
	public partial interface IUfAssociatedPage : IPublishedElement
	{
		/// <summary>Associated Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent AssociatedPage { get; }
	}

	/// <summary>UF.AssociatedPage</summary>
	[PublishedModel("ufAssociatedPage")]
	public partial class UfAssociatedPage : PublishedElementModel, IUfAssociatedPage
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const string ModelTypeAlias = "ufAssociatedPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UfAssociatedPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public UfAssociatedPage(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Associated Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("associatedPage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent AssociatedPage => GetAssociatedPage(this);

		/// <summary>Static getter for Associated Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetAssociatedPage(IUfAssociatedPage that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("associatedPage");
	}
}
