//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.10.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>UF.FancyNextPrevious</summary>
	[PublishedModel("ufFancyNextPrevious")]
	public partial class UfFancyNextPrevious : PublishedElementModel, IUfLink, IUfNextPrevious, IUfSummary, IUfTitle
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const string ModelTypeAlias = "ufFancyNextPrevious";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UfFancyNextPrevious, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public UfFancyNextPrevious(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("link")]
		public global::Umbraco.Web.Models.Link Link => global::Umbraco.Web.PublishedModels.UfLink.GetLink(this);

		///<summary>
		/// Next Link Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("nextLinkText")]
		public string NextLinkText => global::Umbraco.Web.PublishedModels.UfNextPrevious.GetNextLinkText(this);

		///<summary>
		/// Next Page Override
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("nextPageOverride")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent NextPageOverride => global::Umbraco.Web.PublishedModels.UfNextPrevious.GetNextPageOverride(this);

		///<summary>
		/// Previous Link Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("previousLinkText")]
		public string PreviousLinkText => global::Umbraco.Web.PublishedModels.UfNextPrevious.GetPreviousLinkText(this);

		///<summary>
		/// Previous Page Override
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("previousPageOverride")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent PreviousPageOverride => global::Umbraco.Web.PublishedModels.UfNextPrevious.GetPreviousPageOverride(this);

		///<summary>
		/// Text Only Link Field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("textOnlyLinkField")]
		public string TextOnlyLinkField => global::Umbraco.Web.PublishedModels.UfNextPrevious.GetTextOnlyLinkField(this);

		///<summary>
		/// Summary
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("summary")]
		public global::System.Web.IHtmlString Summary => global::Umbraco.Web.PublishedModels.UfSummary.GetSummary(this);

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("title")]
		public string Title => global::Umbraco.Web.PublishedModels.UfTitle.GetTitle(this);
	}
}
