//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.10.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ufGalleryDisplaySettings"
	/// <summary>UF.GalleryDisplaySettings</summary>
	public partial interface IUfGalleryDisplaySettings : IPublishedElement
	{
		/// <summary>Amount of Columns</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		decimal AmountOfColumns { get; }

		/// <summary>Amount of Columns on Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		decimal AmountOfColumnsOnTablet { get; }

		/// <summary>Is Masonry</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		bool IsMasonry { get; }

		/// <summary>Open Images In Lightbox</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		bool OpenImagesInLightbox { get; }
	}

	/// <summary>UF.GalleryDisplaySettings</summary>
	[PublishedModel("ufGalleryDisplaySettings")]
	public partial class UfGalleryDisplaySettings : PublishedElementModel, IUfGalleryDisplaySettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const string ModelTypeAlias = "ufGalleryDisplaySettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UfGalleryDisplaySettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public UfGalleryDisplaySettings(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Amount of Columns
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("amountOfColumns")]
		public decimal AmountOfColumns => GetAmountOfColumns(this);

		/// <summary>Static getter for Amount of Columns</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static decimal GetAmountOfColumns(IUfGalleryDisplaySettings that) => that.Value<decimal>("amountOfColumns");

		///<summary>
		/// Amount of Columns on Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("amountOfColumnsOnTablet")]
		public decimal AmountOfColumnsOnTablet => GetAmountOfColumnsOnTablet(this);

		/// <summary>Static getter for Amount of Columns on Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static decimal GetAmountOfColumnsOnTablet(IUfGalleryDisplaySettings that) => that.Value<decimal>("amountOfColumnsOnTablet");

		///<summary>
		/// Is Masonry
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("isMasonry")]
		public bool IsMasonry => GetIsMasonry(this);

		/// <summary>Static getter for Is Masonry</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static bool GetIsMasonry(IUfGalleryDisplaySettings that) => that.Value<bool>("isMasonry");

		///<summary>
		/// Open Images In Lightbox
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("openImagesInLightbox")]
		public bool OpenImagesInLightbox => GetOpenImagesInLightbox(this);

		/// <summary>Static getter for Open Images In Lightbox</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static bool GetOpenImagesInLightbox(IUfGalleryDisplaySettings that) => that.Value<bool>("openImagesInLightbox");
	}
}
