//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.10.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "ufNextPrevious"
	/// <summary>UF.NextPrevious</summary>
	public partial interface IUfNextPrevious : IPublishedElement
	{
		/// <summary>Next Link Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		string NextLinkText { get; }

		/// <summary>Next Page Override</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent NextPageOverride { get; }

		/// <summary>Previous Link Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		string PreviousLinkText { get; }

		/// <summary>Previous Page Override</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent PreviousPageOverride { get; }

		/// <summary>Text Only Link Field</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		string TextOnlyLinkField { get; }
	}

	/// <summary>UF.NextPrevious</summary>
	[PublishedModel("ufNextPrevious")]
	public partial class UfNextPrevious : PublishedElementModel, IUfNextPrevious
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const string ModelTypeAlias = "ufNextPrevious";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UfNextPrevious, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public UfNextPrevious(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Next Link Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("nextLinkText")]
		public string NextLinkText => GetNextLinkText(this);

		/// <summary>Static getter for Next Link Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static string GetNextLinkText(IUfNextPrevious that) => that.Value<string>("nextLinkText");

		///<summary>
		/// Next Page Override
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("nextPageOverride")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent NextPageOverride => GetNextPageOverride(this);

		/// <summary>Static getter for Next Page Override</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetNextPageOverride(IUfNextPrevious that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("nextPageOverride");

		///<summary>
		/// Previous Link Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("previousLinkText")]
		public string PreviousLinkText => GetPreviousLinkText(this);

		/// <summary>Static getter for Previous Link Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static string GetPreviousLinkText(IUfNextPrevious that) => that.Value<string>("previousLinkText");

		///<summary>
		/// Previous Page Override
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("previousPageOverride")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent PreviousPageOverride => GetPreviousPageOverride(this);

		/// <summary>Static getter for Previous Page Override</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetPreviousPageOverride(IUfNextPrevious that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("previousPageOverride");

		///<summary>
		/// Text Only Link Field
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("textOnlyLinkField")]
		public string TextOnlyLinkField => GetTextOnlyLinkField(this);

		/// <summary>Static getter for Text Only Link Field</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static string GetTextOnlyLinkField(IUfNextPrevious that) => that.Value<string>("textOnlyLinkField");
	}
}
